TestProject.Web/Models/ErrorViewModel.cs
using System;

namespace TestProject.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestProject.Web/Models/UrlModel.cs
namespace TestProject.Web.Models
{
    public class UrlModel
    {
        public string Url { get; set; }
    }
}

TestProject.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TestProject.Web.Models;

namespace TestProject.Web.Controllers
{
	public class HomeController : Controller
	{
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Index(UrlModel responseModel)
		{
			return Redirect(responseModel.Url);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TestProject.Web/Controllers/ResponseTimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestProject.BLL.Services.Interfaces;

namespace TestProject.Web.Controllers
{
    public class ResponseTimeController : Controller
    {
        private readonly IResponseTimeService _responseTimeService;

        public ResponseTimeController(IResponseTimeService responseTimeService)
        {
            _responseTimeService = responseTimeService;
        }

        public async Task<IActionResult> GetResponseTime()
        {
            var responseModel = await _responseTimeService.GetAllResponseTime();
            return View(responseModel);
        }
    }
}

TestProject.Web/Views/Home/Index.cshtml
@model UrlModel

@{
    ViewData["Title"] = "Home Page";
}
    <div class="row">
        <div>
            @{

                var mwres = Context.Response.Headers["Response-Time-ms"];
        }

        @mwres
    </div>
    <div class="col-md-8">
        <section>
            <form asp-controller="Home" asp-action="Index" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
                <h4>Enter url</h4>
                <hr />
                <div class="form-group">
                    <label asp-for="Url" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Url" class="form-control" />
                        <span asp-validation-for="Url" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default">GO TO</button>
                    </div>
                </div>
            </form>
        </section>
    </div>
    </div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TestProject.Web/Views/ResponseTime/GetResponseTime.cshtml
@model TestProject.BLL.Models.ResponseTimesModel
@{
    ViewData["Title"] = "GetResponseTime";
}

<h1>GetResponseTime</h1>

<div>
    @{

        var mwres = Context.Response.Headers["Response-Time-ms"];
    }
    @mwres
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                DateCreate
            </th>
            <th>
                Response
            </th>
            <th>
                MinTime
            </th>
            <th>
                MaxTime
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Request)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MinTime) ms
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxTime) ms
                </td>
            </tr>
        }
    </tbody>
</table>

TestProject.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestProject.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResponseTime" asp-action="GetResponseTime">Response Times</a>
                        </li>
                        @{
                            var time = Context.Response.Headers["Response-Time-ms"];
                        }
                        <li class="nav-item">
                            <p>
                                @time
                            </p>
                        </li>

                    </ul>
                </div>
            </div>
            <div>
                @{

                    var mwres = Context.Response.Headers["Response-Time-ms"];

                }

                @mwres
            </div>

        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div>@Context.Response.Headers["Response-Time-ms"]</div>
        <div>@Context.Request.Headers["Response-Time-ms"]</div>*@
        <div class="container">
            &copy; 2020 - TestProject.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>